title: Another Fullstack Developer's blog
description: "Blog about web development, crypto, linux and other random stuff"
author:
  name: "ijarmar"
  email: "someone@somewebsite.somedomain"
  url: "https://ijarmar.github.io"

baseurl: /

source: .
destination: ./_site
permalink: /:title
paginate: 5
paginate_path: /page/:num/

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

future: true
plugins:
  - jekyll-seo-tag
  - jekyll-paginate
  - jekyll-sitemap

# Custom variables
owner : "ijarmar"
year : "2020"
